In [3]:
import numpy as np

# Define the matrix
A = np.array([[1, 1, 1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1, 1, 0],
              [1, 1, 1, 1, 1, 0, 1],
              [1, 1, 1, 1, 0, 1, 1],
              [1, 1, 1, 0, 1, 0, 0],
              [1, 1, 0, 1, 0, 1, 0],
              [1, 0, 1, 1, 0, 0, 1]])

for n in range(2, 10):
    # Raise the matrix to the power n
    A_power_n = np.linalg.matrix_power(A, n)
    
    print(f"A^{n} =\n", A_power_n)


A^2 =
 [[7 6 6 6 4 4 4]
 [6 6 5 5 4 4 3]
 [6 5 6 5 4 3 4]
 [6 5 5 6 3 4 4]
 [4 4 4 3 4 2 2]
 [4 4 3 4 2 4 2]
 [4 3 4 4 2 2 4]]
A^3 =
 [[37 33 33 33 23 23 23]
 [33 30 29 29 21 21 19]
 [33 29 30 29 21 19 21]
 [33 29 29 30 19 21 21]
 [23 21 21 19 16 13 13]
 [23 21 19 21 13 16 13]
 [23 19 21 21 13 13 16]]
A^4 =
 [[205 182 182 182 126 126 126]
 [182 163 161 161 113 113 110]
 [182 161 163 161 113 110 113]
 [182 161 161 163 110 113 113]
 [126 113 113 110  81  76  76]
 [126 113 110 113  76  81  76]
 [126 110 113 113  76  76  81]]
A^5 =
 [[1129 1003 1003 1003  695  695  695]
 [1003  893  890  890  619  619  614]
 [1003  890  893  890  619  614  619]
 [1003  890  890  893  614  619  619]
 [ 695  619  619  614  433  425  425]
 [ 695  619  614  619  425  433  425]
 [ 695  614  619  619  425  425  433]]
A^6 =
 [[6223 5528 5528 5528 3830 3830 3830]
 [5528 4914 4909 4909 3405 3405 3397]
 [5528 4909 4914 4909 3405 3397 3405]
 [5528 4909 4909 4914 3397 3405 3405]
 [3830 3405 3405 3397 2366 2353 2353]
 